import { createHash } from "crypto"
import fs from "fs"
import path from "path"
import { QuartzEmitterPlugin } from "../types"
import { write } from "./helpers"
import { FilePath, FullSlug, QUARTZ, joinSegments, slugifyFilePath } from "../../util/path"
import { glob } from "../../util/glob"

const rev = (data: string | Buffer): string =>
  createHash("md5").update(data).digest("hex").slice(0, 8)

const fileRev = async (filePath: string, fallback: string): Promise<string> => {
  try {
    return rev(await fs.promises.readFile(filePath))
  } catch {
    return fallback
  }
}

export const PWA: QuartzEmitterPlugin = () => ({
  name: "PWA",

  externalResources() {
    const swScript = `if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js')
      .catch(err => console.warn('SW registration failed:', err))
  })
}`
    return {
      js: [
        {
          loadTime: "afterDOMReady" as const,
          contentType: "inline" as const,
          script: swScript,
          spaPreserve: true,
        },
      ],
    }
  },

  async *emit(ctx, content) {
    const cfg = ctx.cfg.configuration
    // Emitters run in parallel, so output files cannot be read here.
    // Revisions are derived from *sources*: markdown text for pages,
    // vault files for images, quartz/static for static assets.
    const buildStamp = rev(String(Date.now()))
    const manifest: Record<string, string> = {}

    for (const [_tree, vfile] of content) {
      const slug = vfile.data.slug!
      const url = slug === "index" ? "/" : `/${slug}`
      const source = vfile.value
      manifest[url] =
        source && source.length > 0 ? rev(typeof source === "string" ? source : Buffer.from(source)) : buildStamp
    }

    const imageFiles = await glob(
      "**/*.{png,jpg,jpeg,webp,svg,gif}",
      ctx.argv.directory,
      cfg.ignorePatterns,
    )
    for (const f of imageFiles) {
      // the Assets emitter slugifies file paths on copy (spaces -> dashes),
      // so the served URL differs from the vault path we hash
      manifest[`/${slugifyFilePath(f as FilePath)}`] = await fileRev(
        path.join(ctx.argv.directory, f),
        buildStamp,
      )
    }

    const staticSrc = joinSegments(QUARTZ, "static")
    const staticFiles = await glob("**", staticSrc, [...cfg.ignorePatterns, "giscus/**"])
    for (const f of staticFiles) {
      const src = path.join(staticSrc, f)
      if (!(await fs.promises.stat(src).catch(() => null))?.isFile()) continue
      manifest[`/static/${f}`] = await fileRev(src, buildStamp)
    }

    // Assets generated by other emitters (unreadable here due to parallel emit):
    // tie their revision to the overall content state so they refresh with any
    // content change. All are also runtime-refreshed network-first when online.
    const globalRev = rev(JSON.stringify(Object.entries(manifest).sort()))
    for (const url of [
      "/index.css",
      "/postscript.js",
      "/prescript.js",
      "/404.html",
      "/favicon.ico",
      "/static/contentIndex.json",
    ]) {
      manifest[url] = globalRev
    }

    const webmanifest = {
      name: cfg.pageTitle,
      short_name: "B787",
      description: "Boeing 787 Study Guide",
      start_url: "/",
      display: "standalone",
      background_color: "#FAF8F4",
      theme_color: "#3257BC",
      icons: [{ src: "/static/icon.png", sizes: "any", type: "image/png" }],
    }

    yield write({
      ctx,
      slug: "manifest" as FullSlug,
      ext: ".webmanifest",
      content: JSON.stringify(webmanifest, null, 2),
    })

    const sw = `const CACHE = 'b787-content';
const META = 'b787-meta';
const META_KEY = '/__manifest';
const MANIFEST = ${JSON.stringify(manifest)};
const CHUNK = 25;

const norm = u => new URL(u, self.location.origin).href;

async function readStored() {
  try {
    const meta = await caches.open(META);
    const res = await meta.match(META_KEY);
    return res ? await res.json() : {};
  } catch {
    return {};
  }
}

async function writeStored(stored) {
  const meta = await caches.open(META);
  await meta.put(META_KEY, new Response(JSON.stringify(stored), {
    headers: { 'Content-Type': 'application/json' },
  }));
}

async function broadcast(msg) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const c of clients) c.postMessage(msg);
}

// Incremental sync: fetch only URLs whose revision changed or that are missing
// from the cache. Non-ok responses (e.g. 401 login page) are never cached.
async function syncAll() {
  const stored = await readStored();
  const cache = await caches.open(CACHE);
  const present = new Set((await cache.keys()).map(r => r.url));
  const urls = Object.keys(MANIFEST);
  const total = urls.length;
  const need = urls.filter(u => stored[norm(u)] !== MANIFEST[u] || !present.has(norm(u)));
  let done = total - need.length;
  let failed = [];

  const fetchOne = async u => {
    try {
      const res = await fetch(u, { credentials: 'same-origin', cache: 'no-cache' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      await cache.put(u, res);
      stored[norm(u)] = MANIFEST[u];
      done++;
    } catch {
      failed.push(u);
    }
  };

  const run = async list => {
    for (let i = 0; i < list.length; i += CHUNK) {
      await Promise.all(list.slice(i, i + CHUNK).map(fetchOne));
      await broadcast({ type: 'progress', done, total });
    }
  };

  await run(need);
  const retry = failed;
  failed = [];
  await run(retry);

  // drop entries removed from the site (leave extra runtime-cached URLs alone)
  const manifestSet = new Set(urls.map(norm));
  for (const key of Object.keys(stored)) {
    if (!manifestSet.has(key)) {
      await cache.delete(key);
      delete stored[key];
    }
  }
  await writeStored(stored);
  await broadcast({ type: 'complete', cached: done, total, failed: failed.length });
}

async function status() {
  const stored = await readStored();
  const cache = await caches.open(CACHE);
  const present = new Set((await cache.keys()).map(r => r.url));
  const urls = Object.keys(MANIFEST);
  const cached = urls.filter(u => present.has(norm(u)) && stored[norm(u)] === MANIFEST[u]).length;
  return { type: 'status', cached, total: urls.length };
}

self.addEventListener('install', e => {
  e.waitUntil(Promise.all([syncAll(), self.skipWaiting()]));
});

self.addEventListener('activate', e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(keys.filter(k => k !== CACHE && k !== META).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('message', e => {
  const msg = e.data || {};
  if (msg.type === 'status') {
    e.waitUntil(status().then(s => e.source && e.source.postMessage(s)));
  } else if (msg.type === 'backfill') {
    e.waitUntil(syncAll());
  }
});

self.addEventListener('fetch', e => {
  if (e.request.method !== 'GET') return;
  const url = new URL(e.request.url);
  if (url.origin !== location.origin) return;

  const isAsset = url.pathname.startsWith('/static/') ||
    /\\.(png|jpe?g|webp|svg|gif|woff2?|ttf|otf)$/i.test(url.pathname);

  if (isAsset) {
    // Cache-first for images and static assets
    e.respondWith(
      caches.match(e.request).then(cached => {
        if (cached) return cached;
        return fetch(e.request).then(res => {
          if (res.ok) {
            const clone = res.clone();
            caches.open(CACHE).then(c => c.put(e.request, clone));
          }
          return res;
        });
      })
    );
  } else {
    // Network-first with offline fallback for HTML
    e.respondWith(
      fetch(e.request).then(res => {
        if (res.ok) {
          const clone = res.clone();
          caches.open(CACHE).then(c => c.put(e.request, clone));
        }
        return res;
      }).catch(() =>
        caches.match(e.request, { ignoreSearch: true })
          .then(cached => cached || caches.match('/'))
      )
    );
  }
});`

    yield write({
      ctx,
      slug: "sw" as FullSlug,
      ext: ".js",
      content: sw,
    })
  },

  async *partialEmit() {},
})
